/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface MarkdownOptions {
  enableTables?: boolean
  enableFootnotes?: boolean
  enableStrikethrough?: boolean
  enableTasklists?: boolean
  enableSmartPunctuation?: boolean
  enableHeadingAttributes?: boolean
  enableYamlStyleMetadataBlocks?: boolean
  enablePlusesDelimitedMetadataBlocks?: boolean
  enableOldFootnotes?: boolean
  enableMath?: boolean
  enableGfm?: boolean
}

export declare function parse(markdown: string, options?: MarkdownOptions | undefined | null): string

export declare function renderHtml(markdown: string, options?: MarkdownOptions | undefined | null): string
